server:
  port: 8080

spring:
  application:
    name: ship-service
    version: 1.0.0-SNAPSHOT
    description: Ship service provides the facility to add, update, remove and view the ship details on request
  jpa:
    showSql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/ship-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always

jwt:
  token:
    validity: 180000
    prefix: Bearer
  signing:
    key: PUT_YOUR_KEY_HERE
  header:
    string: Authorization
  authorities:
    key: roles

info:
  appName: ${spring.application.name}
  descripton: ${spring.application.description}
  version: ${spring.application.version}
